// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RescueHub.Infrastructure.SqlServer.Persistence;

#nullable disable

namespace RescueHub.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818082255_AddNewEntity")]
    partial class AddNewEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.AuditLogDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.DonationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("DonatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("DonatorId");

                    b.ToTable("Donations", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.DonationTransactionDataModel", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("DonationId");

                    b.ToTable("DonationTransactions", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.InventoryTransactionDataModel", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("TaskId");

                    b.ToTable("InventoryTransactions", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.NotificationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.ReliefRequestDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("CoordinatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("EstimatedAffectedPeople")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedAffectedRadiusKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("ReliefImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestedResource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.ToTable("ReliefRequests", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.ReliefTaskDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequiredVolunteers")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("Status");

                    b.ToTable("ReliefTasks", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.RoleDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.SkillDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.SupplyDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Supplies", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.TaskAssignmentDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignmentSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("Status");

                    b.HasIndex("TaskId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("TaskAssignments", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.TaskSkillDataModel", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TaskId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("TaskSkills", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Province");

                    b.HasIndex("RoleId");

                    b.HasIndex("Status");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.VolunteerDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CVUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ApprovedBy");

                    b.ToTable("Volunteers", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.VolunteerEngagementDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformanceAssessment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("VolunteerId", "RequestId")
                        .IsUnique();

                    b.ToTable("VolunteerEngagements", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.VolunteerSkillDataModel", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("VolunteerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("VolunteerSkills", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("Province");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseInventoryDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupplyId");

                    b.HasIndex("WarehouseId", "SupplyId")
                        .IsUnique();

                    b.ToTable("WarehouseInventories", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseTransactionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("WarehouseInventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WarehouseInventoryId");

                    b.ToTable("WarehouseTransactions", (string)null);
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.AuditLogDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.DonationDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "Donator")
                        .WithMany("Donations")
                        .HasForeignKey("DonatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Donator");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.DonationTransactionDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.DonationDataModel", "Donation")
                        .WithMany("Transactions")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.WarehouseTransactionDataModel", "Transaction")
                        .WithOne("DonationTransaction")
                        .HasForeignKey("RescueHub.Infrastructure.SqlServer.Models.DonationTransactionDataModel", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.InventoryTransactionDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.ReliefTaskDataModel", "Task")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.WarehouseTransactionDataModel", "Transaction")
                        .WithOne("InventoryTransaction")
                        .HasForeignKey("RescueHub.Infrastructure.SqlServer.Models.InventoryTransactionDataModel", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.NotificationDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.ReliefRequestDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "Coordinator")
                        .WithMany("CoordinatedReliefRequests")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "Requester")
                        .WithMany("ReliefRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinator");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.ReliefTaskDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.ReliefRequestDataModel", "Request")
                        .WithMany("Tasks")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.TaskAssignmentDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "Assigner")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.ReliefTaskDataModel", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.VolunteerDataModel", "Volunteer")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assigner");

                    b.Navigation("Task");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.TaskSkillDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.SkillDataModel", "Skill")
                        .WithMany("TaskSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.ReliefTaskDataModel", "Task")
                        .WithMany("TaskSkills")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.RoleDataModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.VolunteerDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "User")
                        .WithOne("Volunteer")
                        .HasForeignKey("RescueHub.Infrastructure.SqlServer.Models.VolunteerDataModel", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.VolunteerEngagementDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.ReliefRequestDataModel", "Request")
                        .WithMany("VolunteerEngagements")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.VolunteerDataModel", "Volunteer")
                        .WithMany("Engagements")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.VolunteerSkillDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.SkillDataModel", "Skill")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.VolunteerDataModel", "Volunteer")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseInventoryDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.SupplyDataModel", "Supply")
                        .WithMany("WarehouseInventories")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.WarehouseDataModel", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supply");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseTransactionDataModel", b =>
                {
                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RescueHub.Infrastructure.SqlServer.Models.WarehouseInventoryDataModel", "WarehouseInventory")
                        .WithMany("Transactions")
                        .HasForeignKey("WarehouseInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("WarehouseInventory");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.DonationDataModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.ReliefRequestDataModel", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("VolunteerEngagements");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.ReliefTaskDataModel", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("TaskSkills");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.RoleDataModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.SkillDataModel", b =>
                {
                    b.Navigation("TaskSkills");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.SupplyDataModel", b =>
                {
                    b.Navigation("WarehouseInventories");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.UserDataModel", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("AuditLogs");

                    b.Navigation("CoordinatedReliefRequests");

                    b.Navigation("Donations");

                    b.Navigation("Notifications");

                    b.Navigation("ReliefRequests");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.VolunteerDataModel", b =>
                {
                    b.Navigation("Engagements");

                    b.Navigation("TaskAssignments");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseDataModel", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseInventoryDataModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RescueHub.Infrastructure.SqlServer.Models.WarehouseTransactionDataModel", b =>
                {
                    b.Navigation("DonationTransaction");

                    b.Navigation("InventoryTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
